import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { AppFooter } from "../components/AppFooter";
import { AppHeader } from "../components/AppHeader";
import { EventList } from "../components/EventList";
import { AppButton } from "../elements/AppButton";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen">
      <Head>
        <title>BlockParty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AppHeader />
      <div
        className="h-screen bg-center"
        style={{
          background: "url('/img-hero.png')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="container flex mx-auto h-4/5">
          <section className="flex flex-col w-1/2 gap-4 mt-auto">
            <h1 className="uppercase">IRL with frens.</h1>
            <span className="text-lg leading-[28px]">
              Web3 is better in real life. Meet the intelligent and interesting
              people from your trustless community.
            </span>
            <div className="flex gap-6">
              <a href="#discover">
                <AppButton>Discover</AppButton>
              </a>
              <Link href={"/create"}>
                <AppButton variant="secondary">Create Invite</AppButton>
              </Link>
            </div>
          </section>
          <section></section>
        </div>
      </div>

      <section id="discover">
        <EventList />
      </section>
      <div className="container mx-auto">
        <AppFooter />
      </div>
    </div>
  );
};

export default Home;
